Fix: Missing navigation bar ordering description (fixes #162)
adaptlearning/adapt-contrib-pageLevelProgress pull request #182
Opened 2023-05-01 14:03 UTC by swashbuck

Fixes #162 

### Fix
* Adds a description (tooltip) for the `_navOrder` property
* Minor adjustments to `_drawerPosition` - Use 'description' instead of 'help' in _course.schema.json_, missing space, and move closer to 'title'

2023-05-01 15:12 UTC, oliverfoster approved these changes
👀

2023-05-03 09:44 UTC, cahirodoherty-learningpool approved these changes
👀

2023-05-03 10:06 UTC, kirsty-hames requested changes

2023-05-03 10:06 UTC, kirsty-hames commented on properties.schema
> +      "help": "Determines the order in which the page level progress is displayed in the navigation bar. Negative numbers (e.g. -100) are left-aligned. Positive numbers (e.g. 100) are right-aligned."
'help' needs replacing with 'description'

2023-05-03 10:06 UTC, kirsty-hames commented on properties.schema
> +      "help": "Determines the starting position of the drawer to open.",
'help' needs replacing with 'description'

2023-05-03 10:07 UTC, kirsty-hames requested changes
I've left a couple of comments but it's a +1 from me thanks @swashbuck

2023-05-03 11:46 UTC, kirsty-hames approved these changes

2023-05-03 11:47 UTC, merged