Fix: Return correct calculation for presentation components with items (fixes #228)
adaptlearning/adapt-contrib-pageLevelProgress pull request #229
Opened 2024-06-04 14:08 UTC by swashbuck

Fix #228 

### Fix
* TBD

### Testing
1. TBD

2024-06-04 14:50 UTC, oliverfoster requested changes

2024-06-04 14:50 UTC, oliverfoster commented on js/PageLevelProgressIndicatorView.js
> +    const isComplete = this.model.get('_isComplete');
```suggestion
    const isComplete = this.model.get('_isComplete');
    if (isComplete) return 100;
```

2024-06-04 14:50 UTC, oliverfoster commented on js/PageLevelProgressIndicatorView.js
> +    return isComplete ? 100 : 0;
```suggestion
    return 0
```

2024-06-04 14:50 UTC, oliverfoster commented on js/PageLevelProgressIndicatorView.js
> +      if (isComplete) return 100;
```suggestion
```

2024-06-04 14:54 UTC, oliverfoster approved these changes

2024-06-07 08:07 UTC, cahirodoherty-learningpool approved these changes
👀

2024-06-07 13:48 UTC, joe-allen-89 approved these changes
👍

2024-06-07 13:48 UTC, merged